function images = initialize_empty_images_structure()

    images = struct( ...
        'figId', {'a','b','c','d','e','f','g','h','i','j','k','l'}, ...
        'filename', { ...
            'linear_pictures/sb/IMG_5959.JPG', ...
            'linear_pictures/sb/IMG_5955.JPG', ...
            'linear_pictures/sb/IMG_5962.JPG', ...
            'linear_pictures/sb/IMG_5965.JPG', ...
            'linear_pictures/sb/IMG_5957.JPG', ...
            'linear_pictures/sb/IMG_5954.JPG', ...
            'linear_pictures/sb/IMG_5961.JPG', ...
            'linear_pictures/sb/IMG_5964.JPG', ...
            'linear_pictures/sb/IMG_5956.JPG', ...
            'linear_pictures/sb/IMG_5953.JPG', ...
            'linear_pictures/sb/IMG_5960.JPG', ...
            'linear_pictures/sb/IMG_5963.JPG'}, ...
        'img', [], ...
        'pts', []);

end
